### PR TITLE
X-platform Run on Startup option

### PR DESCRIPTION
**Pull request by MrFancyMonocle**

### CODE REVIEW

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2.win32.exe](https://github.com/Storj/driveshare-gui/releases/download/untagged-b9847059c9b22afaff18/driveshare_0.4.2.win32.exe) sha: 5cf2f9a5c9f34618b38984375a36fd86eea280b8.exe

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2.dmg](https://github.com/Storj/driveshare-gui/releases/download/untagged-b9847059c9b22afaff18/driveshare_0.4.2.dmg) sha: 5cf2f9a5c9f34618b38984375a36fd86eea280b8.dmg

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-b9847059c9b22afaff18/driveshare_0.4.2_amd64.deb) sha: 5cf2f9a5c9f34618b38984375a36fd86eea280b8.deb

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-b9847059c9b22afaff18/driveshare_0.4.2_amd64.deb) sha: 07cabd1a3ffe0d78e4a382f8fc6b1ed898f3b40d.deb

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2.dmg](https://github.com/Storj/driveshare-gui/releases/download/untagged-b9847059c9b22afaff18/driveshare_0.4.2.dmg) sha: 07cabd1a3ffe0d78e4a382f8fc6b1ed898f3b40d.dmg

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2.win32.exe](https://github.com/Storj/driveshare-gui/releases/download/untagged-b9847059c9b22afaff18/driveshare_0.4.2.win32.exe) sha: 07cabd1a3ffe0d78e4a382f8fc6b1ed898f3b40d.exe

**Comment by super3** [comment]
@littleskunk Please review.

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-f1364a28d6b364f17179/driveshare_0.4.2_amd64.deb) sha: 07cabd1a3ffe0d78e4a382f8fc6b1ed898f3b40d.deb

**Comment by littleskunk** [comment]
Not working with the osx binary. I can set the automatic start flag but if i restart driveshare-gui the flag is missing.

Same test is working with ubuntu. The flag is still there after a restart of driveshare. Addition testcase worked on ubunto as well: start gui, start farming, set the flag and restart the pc without closing the gui or any other action.

System startup could be the wrong label. I loged in with a different user and as expectet driveshare did not start. A better label would be "user logon".

No time for the windows test. I will do that tomorrow.

**Comment by littleskunk** [comment]
Not working on windows. Flag is set after a driveshare restart. Driveshare starts after PC restart but only the gui starts. Somebody has to press the start button. I would expect that driveshare starts farming without user input.

Same problem with ubuntu. Driveshare don't start farming.

**Comment by MrFancyMonocle** [comment]
So after some discussion, we're going to move forward by removing the developer "npm start" script run-at-login option; it simply doesn't make sense to try to maintain two startup options and either presents some confusing scenarios to users or implements an ugly solution in the code to workaround issues that most users would never encounter. Closing this pull and will reopen with slimmer code.

**Pull request closed without merging**
