### PR TITLE
Minor Behavior Changes

### PR DESCRIPTION
**Pull request by MrFancyMonocle**
For #159

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 6f0be56573ccef1c0e5b2557f9ddaa8db73854af
[driveshare_0.5.0_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-8b7d09cbf2ae328f1d11/driveshare_0.5.0_amd64.deb)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 540da747799551f21d235a6a631584ee8f4da087
[driveshare_0.5.0_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-8b7d09cbf2ae328f1d11/driveshare_0.5.0_amd64.deb)

**Comment by MrFancyMonocle** [comment]
There's some very odd behavior that's stemming from this version of Electron's system tray clicks across different platforms. I'll be reporting a bug for this. The only way that affects this release is that on Mac, left and right clicking will result in the context menu opening, instead of left-clicking restoring and focusing the window (works correctly on windows), so it's not critical.

**Comment by MrFancyMonocle** [comment]
Found a workaround to the mac "click" handling issues; inserted here.

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: d372e08f9f793d25f77770a3955ad7d388ba9de2
[driveshare_0.5.0_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-8b7d09cbf2ae328f1d11/driveshare_0.5.0_amd64.deb)

**Comment by gordonwritescode** [comment]
LGTM

**Pull request merged**
