### PR TITLE
X-Platform Run on User Login

### PR DESCRIPTION
**Pull request by MrFancyMonocle**

### CODE REVIEW

**Comment by MrFancyMonocle** [comment]
Closes #88

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [](null) sha: 57cff9a49ea264e5632d5987cf227a2235f51daa.deb

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [](null) sha: 57cff9a49ea264e5632d5987cf227a2235f51daa.deb

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2_amd64.deb) sha: 57cff9a49ea264e5632d5987cf227a2235f51daa.deb

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2.win32.exe](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2.win32.exe) sha: 57cff9a49ea264e5632d5987cf227a2235f51daa.exe

**Comment by littleskunk** [comment]
autobin binary (only available for team members): [driveshare_0.4.2.dmg](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2.dmg) sha: 57cff9a49ea264e5632d5987cf227a2235f51daa.dmg

**Comment by littleskunk** [comment]
Lets start with the positiv tests. I can set the flag on osx, windows and linux. The label "Launch Driveshare on User Logon" is very good. Driveshare starts after logon. Only one thing doesn't work.

>The app need to be able to keep track of its late "state" and re-run that state when the computer is restarted. So if I started Drives 1 and 2 and left them running, those need to start back up when the computer starts back up
> #88

Driveshare doesn't start farming. That was the last "state". Tested on osx, windows, ubuntu.

**Comment by littleskunk** [comment]
autobin binaries (only available for team members) 57cff9a49ea264e5632d5987cf227a2235f51daa
[driveshare_0.4.2.dmg](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2.dmg)
[driveshare_0.4.2.win32.exe](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2.win32.exe)
[driveshare_0.4.2_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2_amd64.deb)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 57cff9a49ea264e5632d5987cf227a2235f51daa
[driveshare_0.4.2.dmg](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2.dmg)
[driveshare_0.4.2.win32.exe](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2.win32.exe)
[driveshare_0.4.2_amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-2881382eb2718a9644e0/driveshare_0.4.2_amd64.deb)

**Comment by gordonwritescode** [comment]
:shipit:

**Pull request merged**
