### PR TITLE
Update master with the latest develop (tagged at v0.5.1)

### PR DESCRIPTION
**Pull request by gordonwritescode**
PR includes bug fixes, including corrupted settings fix as well as OS specific improvements.

### CODE REVIEW

**Comment by gordonwritescode** [comment]
@littleskunk when you get a moment, can you review/test/merge and publish the release for v0.5.1 (already tagged).

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: da338b7efd67792053bc2281f277414f5db9779c
[driveshare_0.5.1.amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-c0531ddff39e131cdcb8/driveshare_0.5.1.amd64.deb)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 184ad6fa10963e0ba46df81bbc42ad8ae7d33041
[driveshare_0.5.1.amd64.deb](https://github.com/Storj/driveshare-gui/releases/download/untagged-d46d6d95b2c43e742485/driveshare_0.5.1.amd64.deb)

**Comment by littleskunk** [comment]
Not working on ubuntu. Installation worked but if i try to open driveshare i get an error. I deleted ~/.config/Driveshare but still the same error message.
```
~$ driveshare 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/opt/driveshare/resources/app.asar/lib/userdata.js:9:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

The new Driveshare-gui config folder is empty. Config file is missing.
```
~/.config/DriveShare$ ls
DevTools Extensions
```

**Comment by gordonwritescode** [comment]
@littleskunk yep, looks like you need to install the deps.

```
cd path/to/driveshare-gui && npm install
```

**Comment by littleskunk** [comment]
My fault. My linux build server needs to run npm install --unsafe-perm. That got lost with the last storjnode update. This time fixed with e9a52e99817f26eedd23ea2909bb792e7fd4906e.

Retest with new binary worked. Time to merge.

**Pull request merged**
